const pros = [
  {
    name: "Tyson Ngo",
    age: "21",
    Reigon: "NA",
    IGN: "TenZ",
    Team: "Sentinels",
    Retired: false,
    VCTwinner: true,
    role: "duelist",
    totalEarnings: "$92,300",
    ADR: "158",
    image:
      "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.pinimg.com%2F474x%2F30%2F53%2F32%2F305332833e27a6fb2cf6fc4f4be6f148.jpg&imgrefurl=https%3A%2F%2Fwww.pinterest.com%2Fpin%2Fg-b--851813717031320991%2F&tbnid=cuLRD3mG8pcp_M&vet=12ahUKEwjXjZnmmtv7AhXJGVkFHaVNBIMQMygcegUIARCbAg..i&docid=OwDFpYmVK-5d3M&w=320&h=320&q=tenz%20funny%20pic&ved=2ahUKEwjXjZnmmtv7AhXJGVkFHaVNBIMQMygcegUIARCbAg",
  },

  {
    name: "Ryan Ngo",
    age: "20",
    Reigon: "NA",
    IGN: "Shanks",
    Team: "Rise Nation",
    Retired: true,
    VCTwinner: false,
    role: "duelist",
    totalEarnings: "$8,895",
    ADR: "131.9",
  },

  {
    name: "Pujan Mehta",
    age: "30",
    Reigon: "NA",
    IGN: "FNS",
    Team: "NRG",
    Retired: false,
    VCTwinner: true,
    role: "IGL",
    totalEarnings: "$148,200",
    ADR: "119.5",
  },

  {
    name: "Timofey Khromov",
    age: "20",
    Reigon: "EU",
    IGN: "Chronicle",
    Team: "FNATIC",
    Retired: false,
    VCTwinner: true,
    role: "Fill",
    totalEarnings: "$110,312",
    ADR: "164.9",
  },

  {
    name: "Jason Susanto",
    age: "18",
    Reigon: "APAC",
    IGN: "f0rsakeN",
    Team: "Paper Rex",
    Retired: false,
    VCTwinner: false,
    role: "duelist",
    totalEarnings: "$77,216",
    ADR: "173",
  },

  {
    name: "Jaccob Whiteaker",
    age: "24",
    Reigon: "NA",
    IGN: "yay",
    Team: "Cloud 9",
    Retired: false,
    VCTwinner: true,
    role: "sentinel",
    totalEarnings: "$137,000",
    ADR: "157.8",
  },
  {
    name: "Bryan Luna",
    age: "23",
    Reigon: "LATAM",
    IGN: "pANcada",
    Team: "Sentinels",
    retired: false,
    VCTwinner: true,
    role: "smokes",
    totalEarnings: "$100,584",
    ADR: "137",
  },

  {
    name: "Ushia Koji",
    age: "27",
    Reigon: "APAC",
    IGN: "Laz",
    Team: "ZETA Division",
    retired: false,
    VCTwinner: false,
    role: "IGL",
    totalEarnings: "61,669",
    ADR: "152.6",
  },

  {
    name: "Gustavo Rossi",
    age: "24",
    Reigon: "LATAM",
    IGN: "Sacy",
    Team: "Sentinels",
    retired: false,
    VCTwinner: false,
    role: "IGL",
    totalEarnings: "$115,892",
    ADR: "157.5",
  },

  {
    name: "Jared Gitlin",
    age: "24",
    Reigon: "NA",
    IGN: "zombs",
    Team: "Sentinels",
    retired: true,
    VCTwinner: true,
    role: "smokes",
    totalEarnings: "$113,500",
    ADR: "109.7",
  },

  {
    name: "Kim Myeong-Kwan",
    age: "20",
    Reigon: "APAC",
    IGN: "MaKo",
    Team: "DRX",
    retired: false,
    VCTwinner: false,
    role: "smokes",
    totalEarnings: "$64,419",
    ADR: "146.1",
  },

  {
    name: "Nikita Sirmitev",
    age: "19",
    Reigon: "EU",
    IGN: "Derke",
    Team: "FNATIC",
    retired: false,
    VCTwinner: false,
    role: "duelist",
    totalEarnings: "$82,435",
    ADR: "199.1",
  },

  {
    name: "Spencer Martin ",
    age: "32",
    Reigon: "NA",
    IGN: "Hiko",
    Team: "100T",
    retired: true,
    VCTWinner: false,
    role: "initiator",
    totalEarnings: "$45,750",
    ADR: "129.8",
  },

  {
    name: "Ayaz Akhmetshin",
    age: "20",
    Reigon: "EU",
    IGN: "nAts",
    Team: "Team Liquid",
    retired: "false",
    VCTwinner: "true",
    role: "smokes",
    totalEarnings: "$110,640",
    ADR: "164.8",
  },

  {
    name: "Ardis Svarenieks",
    age: "24",
    Reigon: "EU",
    IGN: "ardiis",
    Team: "NRG",
    retired: "false",
    VCTwinner: "true",
    role: "initiator",
    ADR: "146.9",
  },

  {
    name: "Jordan Montemurro",
    age: "24",
    Reigon: "NA",
    IGN: "Zellsis",
    Team: "Cloud 9",
    retired: "false",
    VCTwinner: "false",
    role: "duelist",
    ADR: "164.5",
  },
];

console.log(pros);
