const pros = [
  {
    name: "Tyson Ngo",
    age: "21",
    Reigon: "NA",
    IGN: "TenZ",
    Team: "Sentinels",
    Retired: false,
    VCTwinner: true,
    role: "entry",
    totalEarnings: "$92,300",
    ADR: "158",
  },

  {
    name: "Ryan Ngo",
    age: "20",
    Reigon: "NA",
    IGN: "Shanks",
    Team: "Rise Nation",
    Retired: true,
    VCTwinner: false,
    role: "entry",
    totalEarnings: "$8,895",
    ADR: "131.9",
  },

  {
    name: "Pujan Mehta",
    age: "30",
    Reigon: "NA",
    IGN: "FNS",
    Team: "NRG",
    Retired: false,
    VCTwinner: true,
    role: "IGL/Anchor",
    totalEarnings: "$148,200",
    ADR: "119.5",
  },

  {
    name: "Timofey Khromov",
    age: "20",
    Reigon: "EU",
    IGN: "Chronicle",
    Team: "FNATIC",
    Retired: false,
    VCTwinner: false,
    role: "Fill",
    totalEarnings: "$110,312",
    ADR: "164.9",
  },

  {
    name: "Jason Susanto",
    age: "18",
    Reigon: "APAC",
    IGN: "f0rsakeN",
    Team: "Paper Rex",
    Retired: false,
    VCTwinner: false,
    role: "entry",
    totalEarnings: "$77,216",
    ADR: "173",
  },

  {
    name: "Jaccob Whiteaker",
    age: "24",
    Reigon: "NA",
    IGN: "yay",
    Team: "Cloud 9",
    Retired: false,
    VCTwinner: true,
    role: "AWPer",
    totalEarnings: "$137,000",
    ADR: "157.8",
  },
  {
    name: "Bryan Luna",
    age: "23",
    Reigon: "LATAM",
    IGN: "pANcada",
    Team: "Sentinels",
    retired: false,
    VCTwinner: true,
    role: "Smokes",
    totalEarnings: "$100,584",
    ADR: "137",
  },

  {
    name: "Ushia Koji",
    age: "27",
    Reigon: "APAC",
    IGN: "Laz",
    Team: "ZETA Division",
    retired: false,
    VCTwinner: false,
    role: "IGL/Anchor",
    totalEarnings: "61,669",
    ADR: "152.6",
  },

  {
    name: "Gustavo Rossi",
    age: "24",
    Reigon: "LATAM",
    IGN: "Sacy",
    Team: "Sentinels",
    retired: false,
    VCTwinner: false,
    role: "IGL/Initator",
    totalEarnings: "$115,892",
    ADR: "157.5",
  },

  {
    name: "Jared Gitlin",
    age: "24",
    Reigon: "NA",
    IGN: "zombs",
    Team: "Sentinels",
    retired: true,
    VCTwinner: true,
    role: "Smokes",
    totalEarnings: "$113,500",
    ADR: "109.7",
  },

  {
    name: "Kim Myeong-Kwan",
    age: "20",
    Reigon: "APAC",
    IGN: "MaKo",
    Team: "DRX",
    retired: false,
    VCTwinner: false,
    role: "Smokes",
    totalEarnings: "$64,419",
    ADR: "146.1",
  },

  {
    name: "Nikita Sirmitev",
    age: "19",
    Reigon: "EU",
    IGN: "Derke",
    Team: "FNATIC",
    retired: false,
    VCTwinner: false,
    role: "entry/AWPer",
    totalEarnings: "$82,435",
    ADR: "199.1",
  },
];

console.log(pros);
